// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ugYqEDG6LvMIW30_BTC-Xo9LVu-__Qo',
    appId: '1:715284850839:web:3b36e5d83543d663f7a1d2',
    messagingSenderId: '715284850839',
    projectId: 'urbandrop-a2c9d',
    authDomain: 'urbandrop-a2c9d.firebaseapp.com',
    storageBucket: 'urbandrop-a2c9d.appspot.com',
    measurementId: 'G-WQZ6JSZ44W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5cE3TVXoD6iLCZmb5YY1ylmWRqnBH9yc',
    appId: '1:715284850839:android:0dc880771e6f1722f7a1d2',
    messagingSenderId: '715284850839',
    projectId: 'urbandrop-a2c9d',
    storageBucket: 'urbandrop-a2c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsupWbU7Htx6QK0x1oes2aq9ARAoHav_A',
    appId: '1:715284850839:ios:e72f30edd6689844f7a1d2',
    messagingSenderId: '715284850839',
    projectId: 'urbandrop-a2c9d',
    storageBucket: 'urbandrop-a2c9d.appspot.com',
    androidClientId: '715284850839-9gv36pank75bkuk33oh2m26q6qoqurhq.apps.googleusercontent.com',
    iosClientId: '715284850839-qu89tab6ehqm91hj2dvojushs1dd4qso.apps.googleusercontent.com',
    iosBundleId: 'io.urbandrop.merchant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsupWbU7Htx6QK0x1oes2aq9ARAoHav_A',
    appId: '1:715284850839:ios:e72f30edd6689844f7a1d2',
    messagingSenderId: '715284850839',
    projectId: 'urbandrop-a2c9d',
    storageBucket: 'urbandrop-a2c9d.appspot.com',
    androidClientId: '715284850839-9gv36pank75bkuk33oh2m26q6qoqurhq.apps.googleusercontent.com',
    iosClientId: '715284850839-qu89tab6ehqm91hj2dvojushs1dd4qso.apps.googleusercontent.com',
    iosBundleId: 'io.urbandrop.merchant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4ugYqEDG6LvMIW30_BTC-Xo9LVu-__Qo',
    appId: '1:715284850839:web:3b36e5d83543d663f7a1d2',
    messagingSenderId: '715284850839',
    projectId: 'urbandrop-a2c9d',
    authDomain: 'urbandrop-a2c9d.firebaseapp.com',
    storageBucket: 'urbandrop-a2c9d.appspot.com',
    measurementId: 'G-WQZ6JSZ44W',
  );

}